### ISSUE TITLE
Registering DeviareCOM.dll via batch files

### ISSUE THREAD

**Issue by zzbusterzz** [bo3b/Hooking-DX9-Present#1]
We can improve the register call via using batch file code
```
cd %~dp0
regsvr32 DeviareCOM.dll
```
This will allow more users faster execution

**Comment by bo3b** [comment]
Also possible to use their registration free COM via Manifest files, in case that is better.

http://blog.nektra.com/main/2014/10/16/registration-free-activation-of-deviare-hooking-engine-com-in-x86-and-x64-platforms/

**Comment by bo3b** [comment]
I've added this registration free COM to the project, so we no longer need to do regsvr32 here.  A bit tricky to setup, because it doesn't report any errors at all, just fails.  

Seems to work correctly here though, by setting it up via the C# application manifest.

This can now also serve as a working example of RegistrationFreeCOM for Deviare.
