### ISSUE TITLE
Missing linker files in NativePlugin part

### ISSUE THREAD

**Issue by zzbusterzz** [bo3b/Hooking-DX9-Present#2]
When i tried to compile the NativePlugin solution it gave me error saying "NktHookLib.lib" is missing. In case anyone needs this file you can find it here in [3DMigoto](https://github.com/bo3b/3Dmigoto/tree/master/Nektra). "nkthooklib.pdb" this file is not necessary to add but it will give warnings while compiling.
The above result is produced on VS2017 community OS: Windows 10 Build 17134

**Comment by bo3b** [comment]
Interesting oversight on my part. Thanks for the heads up.

Using the files from 3Dmigoto version is good, that is an up to date version that fixes a serious x64 bug.

**Comment by yo1995** [comment]
Thanks for mentioning that. 😄

**Comment by bo3b** [comment]
This should now be fixed.  I restructured the project a bit clarify the uses of the different files, and added all the NktHookLib.lib for building.

This new version also includes the Registration Free COM, so that we don't need regsvr32 here anymore, it is specified in the manifest.

<br>

More importantly, I tested a clean rebuild, by deleting the entire project, and recloning it from here, so I'm confident it should build and run now for either Debug or Release.  x64 use would most likely require some more project level tweaks.
